### ISSUE TITLE
Upgrading to v2.0.0

### ISSUE THREAD

**Issue by ruchiy48** [LinusU/node-append-field#3]
While upgrading the append-field from v1.0.0 to v2.0.0, the application is throwing the error pasted below:

" require() of ES Module D:\NewFolder\Project\node_modules\append-field\index.js from D:\NewFolder\Project\node_modules\multer\lib\make-middleware.js not supported.
Instead change the require of index.js in D:\NewFolder\Project\node_modules\multer\lib\make-middleware.js to a dynamic import() which is available in all CommonJS modules."

Also, tried migrating to node-fetch v2.x from v3.x(which my application was using), as that support CommonJS modules. But still getting the same error.

Could you suggest any way to clear this issue as the prior version is giving threats in infosec scanning.

**Comment by LinusU** [comment]
`append-field` v2 only works with ESM, wheras v1 works with CommonJS.

In order to use v2 you need to be using `import` instead of `require`.

If you cannot migrate to ESM at this point, I suggest staying with v1 of `append-field`. They should work exactly the same.

Here is some more information: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
